### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by elpekenin** [bill88t/cptoml#1]
Posting here just some thoughts, havent really digged the code to understand all of it.

My messy code for TOML can be found [here](https://github.com/elpekenin/circuitpython_toml)

First, i would use longer (more descriptive) names, its kind of difficult to read right now

As per the actual parsing, my steps would be:
1. Trim the raw string. Ie: remove heading and trailing whitspaces with `raw.strip()`
1. Find the strings (quote marks) on it, for now i would focus on `"` and `'` and forget about triple ones (multi-line strings). Perhaps having a class which stores the raw string + positions where the string starts and ends. (Checking there's exactly 2 of the char used to delimit the string, which are right after the equal sign and at the end of the line + any number of the other char)
1. Then, remove the comments looking for `#` OUTSIDE the string, if im not mistaken, your current code would remove anything after a `#`, which would break stuff like storing API tokens or passwords which contain such char
1. For the output, i think it is pretty neat having the `Dotty` class i've implemented, where we can easily read and write elements based on their "global" key
1. I would return the whole datastructure storing the file contents, and some sort of "wrapper" function which only returns a given key from it

Extra: I would also allow bools to be written as `True` (for friendliness with Python) along with the TOML syntax `true`

**Comment by bill88t** [comment]
The internal functions are using short names cause nobody should use them really.
All that startwith `_` are not for use outside of the module.

1. That is done in my `_rcm`.
2. I think I forgot about `"""` entirely, I will have to fix that at some point.
3. I have to check, this could be a serious oversight.
4. I am not quite sure I get what it is.
5. I think I need a `.dump` function too.

**Comment by elpekenin** [comment]
> are not for use outside of the module.

yeah, im aware of that and the underscore should of course be kept, but for maintailability i think (even slightly) longer names would be nice

> _rcm

Yeah, but strip would prevent the need for manual handling

> I am not quite sure I get what it is.

It's basically a wrapper around a dict, which allows indexing (both for getting and setting) with `dictionary["table.subtable.subsubtable.key"]`

**Comment by bill88t** [comment]
Fixed number 3:
`TESTCOMMANDO = "TE#''##ST" # test`
```
>>> cptoml.fetch(item="TESTCOMMANDO", toml="test.toml")
"TE#''##ST"
```

> yeah, im aware of that and the underscore should of course be kept, but for maintailability i think (even slightly) longer names would be nice

I suppose. I will try to swap them.

**Comment by bill88t** [comment]
Alright swapped them now.
Feel free to let me know if the names still feel inadequate.

**Comment by elpekenin** [comment]
Those look good to me 👍

**Comment by bill88t** [comment]
Dotty looks nice, but is something I don't see myself integrating into cptoml.
You aren't gonna need that many keys in any single bit of code.
If you still want it, you can try integrating it yourself.
If you do (or I do) a `.tables`, to get all the available tables, it should be ok.
